name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate Javadoc
        run: ./gradlew aggregateJavadoc

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/javadoc

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in docs/releases/v*.md; do
            if [ -f "$file" ]; then
              VERSION=$(basename "$file" .md)
              if ! gh release view "$VERSION" > /dev/null 2>&1; then
                echo "Creating release for $VERSION"
                gh release create "$VERSION" --title "Release $VERSION" --notes-file "$file"
              else
                echo "Release $VERSION already exists"
              fi
            fi
          done
